<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <Configurations>Debug;Release</Configurations>
        <Platforms>x64</Platforms>
    </PropertyGroup>

</Project>
