namespace LabProject.SourceGenerator;

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public class PlayerServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(PostInitialization);

        var syntaxProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            $"{GeneratorFacts.Namespace}.{GeneratorFacts.PlayerServiceAttributeName}",
            (node, _) => node is ClassDeclarationSyntax,
            (syntaxContext, _) => (Context: syntaxContext, Syntax: (ClassDeclarationSyntax)syntaxContext.TargetNode));

        context.RegisterSourceOutput(
            syntaxProvider.Combine(context.CompilationProvider),
            (productionContext, tuple) => GenerateCode(productionContext, tuple.Left.Syntax, tuple.Right));
    }

    private static void PostInitialization(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource(
            $"{GeneratorFacts.PlayerServiceAttributeName}.g.cs",
            $$"""
              // <auto-generated/>

              using System;

              namespace {{GeneratorFacts.Namespace}}
              {
                  [AttributeUsage(AttributeTargets.Class)]
                  internal class {{GeneratorFacts.PlayerServiceAttributeName}} : Attribute
                  {
                  }
              }
              """);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ClassDeclarationSyntax classSyntax,
        Compilation compilation)
    {
        var serviceName = classSyntax.Identifier.Text;

        if (!classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            var diagnostic = Diagnostic.Create(
                GeneratorFacts.ClassMustBePartial,
                classSyntax.Identifier.GetLocation(),
                serviceName);
            context.ReportDiagnostic(diagnostic);

            return;
        }

        var semanticModel = compilation.GetSemanticModel(classSyntax.SyntaxTree);
        var serviceSymbol = semanticModel.GetDeclaredSymbol(classSyntax);

        if (serviceSymbol is null)
        {
            return;
        }

        var serviceBaseSymbol = serviceSymbol.BaseType;

        if (serviceBaseSymbol is null || serviceBaseSymbol.SpecialType == SpecialType.System_Object)
        {
            var diagnostic = Diagnostic.Create(
                GeneratorFacts.MustInheritFromBaseClass,
                classSyntax.Identifier.GetLocation(),
                classSyntax.Identifier.Text);
            context.ReportDiagnostic(diagnostic);

            return;
        }

        var serviceBaseAttribute = serviceBaseSymbol.GetAttributes()
            .FirstOrDefault(x => x.AttributeClass?.Name == GeneratorFacts.PlayerServiceBaseAttributeName);

        if (serviceBaseAttribute is null)
        {
            var diagnostic = Diagnostic.Create(
                GeneratorFacts.MissingRequiredBaseAttribute,
                classSyntax.Identifier.GetLocation(),
                classSyntax.Identifier.Text,
                serviceBaseSymbol.Name);

            context.ReportDiagnostic(diagnostic);

            return;
        }

        var typeArgument = serviceBaseAttribute.ConstructorArguments[0];
        var playerEventSymbol = (INamedTypeSymbol)typeArgument.Value!;

        if (classSyntax.Parent is not BaseNamespaceDeclarationSyntax namespaceDeclarationSyntax)
        {
            return;
        }

        const string serviceVar = GeneratorFacts.LocalAutoGenPrefix + "service";

        var codeBuilder = new StringBuilder(
            $$"""
              // <auto-generated/>

              using System;
              using System.Collections.Generic;
              using LabApi.Features.Wrappers;

              namespace {{namespaceDeclarationSyntax.Name}}
              {
                  public partial class {{serviceName}}
                  {
                      private static readonly Dictionary<Player, {{serviceName}}> {{GeneratorFacts.ServiceDictionaryName}} = new Dictionary<Player, {{serviceName}}>();
                      
                      private static Func<Player, {{serviceName}}> {{GeneratorFacts.ServiceFactoryName}};
                      
                      public static void {{GeneratorFacts.SetServiceFactoryMethodName}}(Func<Player, {{serviceName}}> factory)
                      {
                          {{GeneratorFacts.ServiceFactoryName}} = factory;
                      }
                      
                      public static {{serviceName}} {{GeneratorFacts.CreateServiceMethodName}}(Player player)
                      {
                          if ({{GeneratorFacts.ServiceFactoryName}} == null)
                          {
                              return null;
                          }
                      
                          var {{serviceVar}} = {{GeneratorFacts.ServiceFactoryName}}(player);
                          
                          {{GeneratorFacts.ServiceDictionaryName}}[player] = {{serviceVar}};
                          
                          return {{serviceVar}};
                      }
                      
                      public static void {{GeneratorFacts.DestroyServiceMethodName}}(Player player)
                      {
                          {{GeneratorFacts.ServiceDictionaryName}}.Remove(player);
                      }
                      
                      public static {{serviceName}} {{GeneratorFacts.GetServiceMethodName}}(Player player)
                      {
                          {{GeneratorFacts.ServiceDictionaryName}}.TryGetValue(player, out var {{serviceVar}});
                          
                          return {{serviceVar}};
                      }

              """);

        var registerCodeBuilder = new StringBuilder(
            $"""

                         {playerEventSymbol.ToDisplayString()}.{GeneratorFacts.PlayerJoinedEvent} += {GeneratorFacts.GlobalHandlerPrefix}{GeneratorFacts.PlayerJoinedEvent};
                         {playerEventSymbol.ToDisplayString()}.{GeneratorFacts.PlayerLeftEvent} += {GeneratorFacts.GlobalHandlerPrefix}{GeneratorFacts.PlayerLeftEvent};
             """);

        var unregisterCodeBuilder = new StringBuilder(
            $"""

                         {playerEventSymbol.ToDisplayString()}.{GeneratorFacts.PlayerJoinedEvent} -= {GeneratorFacts.GlobalHandlerPrefix}{GeneratorFacts.PlayerJoinedEvent};
                         {playerEventSymbol.ToDisplayString()}.{GeneratorFacts.PlayerLeftEvent} -= {GeneratorFacts.GlobalHandlerPrefix}{GeneratorFacts.PlayerLeftEvent};
             """);

        codeBuilder.AppendLine(
            $$"""

                    private static void {{GeneratorFacts.GlobalHandlerPrefix}}{{GeneratorFacts.PlayerJoinedEvent}}({{GeneratorFacts.PlayerJoinedEventArgs}} ev)
                    {
                        var {{serviceVar}} = {{GeneratorFacts.CreateServiceMethodName}}(ev.Player);
                    
                        {{serviceVar}}.{{GeneratorFacts.LocalHandlerPrefix}}{{GeneratorFacts.PlayerJoinedEvent}}(ev);
                    }
                    
                    private static void {{GeneratorFacts.GlobalHandlerPrefix}}{{GeneratorFacts.PlayerLeftEvent}}({{GeneratorFacts.PlayerLeftEventArgs}} ev)
                    {
                        var {{serviceVar}} = {{GeneratorFacts.GetServiceMethodName}}(ev.Player);
                        
                        {{serviceVar}}.{{GeneratorFacts.LocalHandlerPrefix}}{{GeneratorFacts.PlayerLeftEvent}}(ev);
                        
                        {{GeneratorFacts.DestroyServiceMethodName}}(ev.Player);
                    }
            """);

        foreach (var member in serviceSymbol.GetMembers())
        {
            if (member is not IMethodSymbol methodSymbol)
            {
                continue;
            }

            if (!methodSymbol.IsOverride)
            {
                continue;
            }

            var eventName = methodSymbol.Name.Substring(GeneratorFacts.LocalHandlerPrefix.Length);

            if (eventName is GeneratorFacts.PlayerJoinedEvent or GeneratorFacts.PlayerLeftEvent)
            {
                continue;
            }

            var argumentType = methodSymbol.Parameters[0].Type;

            var globalHandlerName = GeneratorFacts.GlobalHandlerPrefix + eventName;

            registerCodeBuilder.Append(
                $"""

                             {playerEventSymbol.ToDisplayString()}.{eventName} += {globalHandlerName};
                 """);

            unregisterCodeBuilder.Append(
                $"""

                             {playerEventSymbol.ToDisplayString()}.{eventName} -= {globalHandlerName};
                 """);

            codeBuilder.AppendLine(
                $$"""

                          private static void {{globalHandlerName}}({{argumentType.ToDisplayString()}} ev)
                          {
                              var {{serviceVar}} = {{GeneratorFacts.GetServiceMethodName}}(ev.Player);
                              
                              {{serviceVar}}.{{methodSymbol.Name}}(ev);
                          }
                  """);
        }

        codeBuilder.AppendLine(
            $$"""

                      public static void {{GeneratorFacts.RegisterServiceMethodName}}()
                      {{{registerCodeBuilder}}
                      }
                      
                      public static void {{GeneratorFacts.UnregisterServiceMethodName}}()
                      {{{unregisterCodeBuilder}}
                      }
              """);

        codeBuilder.Append(
            """
                }
            }
            """);

        context.AddSource($"{serviceName}.g.cs", codeBuilder.ToString());
    }
}