namespace LabProject.SourceGenerator;

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public class PlayerServiceBaseGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(PostInitialization);

        var syntaxProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            $"{GeneratorFacts.Namespace}.{GeneratorFacts.PlayerServiceBaseAttributeName}",
            (node, _) => node is ClassDeclarationSyntax,
            (syntaxContext, _) => (Context: syntaxContext, Syntax: (ClassDeclarationSyntax)syntaxContext.TargetNode));

        context.RegisterSourceOutput(
            syntaxProvider.Combine(context.CompilationProvider),
            (productionContext, tuple) => GenerateCode(productionContext, tuple.Left.Context, tuple.Left.Syntax));
    }

    private static void PostInitialization(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource($"{GeneratorFacts.PlayerServiceBaseAttributeName}.g.cs",
            $$"""
              // <auto-generated/>

              using System;

              namespace {{GeneratorFacts.Namespace}}
              {
                  [AttributeUsage(AttributeTargets.Class)]
                  internal class {{GeneratorFacts.PlayerServiceBaseAttributeName}} : Attribute
                  {
                      public {{GeneratorFacts.PlayerServiceBaseAttributeName}}(Type playerEventType)
                      {
                          this.PlayerEventType = playerEventType;
                      }
                      
                      public Type PlayerEventType { get; set; }
                  }
              }
              """);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        GeneratorAttributeSyntaxContext attributeContext,
        ClassDeclarationSyntax classSyntax)
    {
        var attribute = attributeContext.Attributes[0];

        if (attribute.ConstructorArguments.Length <= 0)
        {
            return;
        }

        var serviceBaseName = classSyntax.Identifier.ToString();

        if (!classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            var diagnostic = Diagnostic.Create(
                GeneratorFacts.ClassMustBePartial,
                classSyntax.Identifier.GetLocation(),
                serviceBaseName);
            context.ReportDiagnostic(diagnostic);

            return;
        }

        if (!classSyntax.Modifiers.Any(SyntaxKind.AbstractKeyword))
        {
            var diagnostic = Diagnostic.Create(
                GeneratorFacts.ClassMustBeAbstract,
                classSyntax.Identifier.GetLocation(),
                serviceBaseName);
            context.ReportDiagnostic(diagnostic);

            return;
        }

        var typeArgument = attribute.ConstructorArguments[0];

        if (typeArgument.Kind != TypedConstantKind.Type || typeArgument.Value is not INamedTypeSymbol playerEventSymbol)
        {
            var diagnostic = Diagnostic.Create(
                GeneratorFacts.InvalidTypeArgument,
                attribute.ApplicationSyntaxReference!.GetSyntax().GetLocation(),
                typeArgument.ToCSharpString());
            context.ReportDiagnostic(diagnostic);

            return;
        }

        if (classSyntax.Parent is not BaseNamespaceDeclarationSyntax namespaceDeclarationSyntax)
        {
            return;
        }

        var codeBuilder = new StringBuilder(
            $$"""
              // <auto-generated/>

              using System;
              using System.Collections.Generic;
              using LabApi.Events.Arguments.PlayerEvents;
              using LabApi.Features.Wrappers;

              namespace {{namespaceDeclarationSyntax.Name}}
              {
                  public abstract partial class {{serviceBaseName}}
                  {
              """);

        foreach (var eventSymbol in playerEventSymbol.GetMembers().OfType<IEventSymbol>())
        {
            var eventName = eventSymbol.Name;

            if (eventSymbol.Type is not INamedTypeSymbol { IsGenericType: true } eventType ||
                eventType.TypeArguments.Length != 1 ||
                eventType.TypeArguments[0] is not INamedTypeSymbol argumentType)
            {
                continue;
            }

            if (!argumentType.MemberNames.Contains("Player"))
            {
                continue;
            }

            var localHandlerName = GeneratorFacts.LocalHandlerPrefix + eventName;

            codeBuilder.AppendLine(
                $$"""

                          protected virtual void {{localHandlerName}}({{argumentType.Name}} ev)
                          {
                          }
                  """);
        }

        codeBuilder.Append(
            """
                }
            }
            """);

        context.AddSource($"{serviceBaseName}.g.cs", codeBuilder.ToString());
    }
}