<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>14</LangVersion>
        <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.2" />
      <PackageReference Include="FFMpegCore" Version="5.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LabProject.Shared\LabProject.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="LabProject.Audio.csproj.user" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(AssembliesPath)Assembly-CSharp-Publicized.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp-firstpass">
            <HintPath>$(AssembliesPath)Assembly-CSharp-firstpass.dll</HintPath>
        </Reference>
        <Reference Include="CommandSystem.Core">
            <HintPath>$(AssembliesPath)CommandSystem.Core.dll</HintPath>
        </Reference>
        <Reference Include="Mirror">
            <HintPath>$(AssembliesPath)Mirror.dll</HintPath>
        </Reference>
        <Reference Include="Mirror.Components">
            <HintPath>$(AssembliesPath)Mirror.Components.dll</HintPath>
        </Reference>
        <Reference Include="mscorlib">
            <HintPath>$(AssembliesPath)mscorlib.dll</HintPath>
        </Reference>
        <Reference Include="netstandard">
            <HintPath>$(AssembliesPath)netstandard.dll</HintPath>
        </Reference>
        <Reference Include="NorthwoodLib">
            <HintPath>$(AssembliesPath)NorthwoodLib.dll</HintPath>
        </Reference>
        <Reference Include="System">
            <HintPath>$(AssembliesPath)System.dll</HintPath>
        </Reference>
        <Reference Include="System.Core">
            <HintPath>$(AssembliesPath)System.Core.dll</HintPath>
        </Reference>
        <Reference Include="System.Memory">
            <HintPath>$(AssembliesPath)System.Memory.dll</HintPath>
        </Reference>
        <Reference Include="System.Runtime">
            <HintPath>$(AssembliesPath)System.Runtime.dll</HintPath>
        </Reference>
        <Reference Include="UniTask">
            <HintPath>..\_References\UniTask.dll</HintPath>
        </Reference>
        <Reference Include="UniTask.DOTween">
            <HintPath>..\_References\UniTask.DOTween.dll</HintPath>
        </Reference>
        <Reference Include="UniTask.Linq">
            <HintPath>..\_References\UniTask.Linq.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(AssembliesPath)UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Physics2DModule">
            <HintPath>$(AssembliesPath)UnityEngine.Physics2DModule.dll</HintPath>
        </Reference>
    </ItemGroup>

    <Target Name="CopyFileAfterBuild" AfterTargets="AfterBuild">
        <Copy
                SourceFiles="$(TargetDir)LabProject.Audio.dll"
                DestinationFolder="$(CopyPath)"
                SkipUnchangedFiles="false" />
    </Target>
</Project>